# Database Configuration for Production
spring.datasource.url=jdbc:mysql://prod-db-server:3306/employee_prod
spring.datasource.username=Deepraj
spring.datasource.password=Deepraj@2004

# Logging Configuration for Production (File Logging with WARN Level)
logging.level.root=WARN
logging.level.com.bridgelabz.employeepayrollapp=ERROR
logging.file.name=logs/production-app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n